#!/usr/bin/env python3
"""Write a complete measured-cell view of the exact-two yaw validation atlas.

This is a reporting tool only. It does not fit models or read the sealed
test/final-test partitions. It joins the broad-model and local-expert scores
already generated by the exact-two audit.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import joblib
import numpy as np


ROOT = Path(__file__).resolve().parents[3]
DEFAULT_SOURCE = ROOT / "live_runs/racing_model_diagnostics_20261008/yaw_full_domain_exact_two_v2"
DEFAULT_OUTPUT = ROOT / "docs/development/YAW_EXACT_TWO_CELL_ATLAS_20261008.md"
SPEED_BINS = range(12)
STEERING_TENTHS = range(-5, 6)


def _load(source: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    report = json.loads((source / "report.json").read_text(encoding="utf-8"))
    atlas = json.loads((source / "validation_atlas.json").read_text(encoding="utf-8"))
    return report, atlas


def _cell_key(speed_bin: int, steer_tenths: int) -> str:
    sign = "+" if steer_tenths >= 0 else ""
    return f"v{speed_bin}-{speed_bin + 1}_steer{sign}{steer_tenths / 10:.1f}"


def _fmt(value: Any, digits: int = 3) -> str:
    if value is None:
        return "—"
    return f"{float(value):.{digits}f}"


def render(report: dict[str, Any], atlas: dict[str, Any],
           source: Path) -> str:
    global_cells = atlas["models"]["global"]["by_speed_and_signed_steering"]
    local_cells = atlas["models"]["local_speed_steering_event_experts"][
        "by_speed_and_signed_steering"]
    predictions = np.load(source / "validation_predictions.npz",
                          allow_pickle=False)
    model_bundle = joblib.load(source / "yaw_models.joblib")
    expert_counts = Counter(
        (int(speed), int(steering))
        for speed, steering, _event in
        model_bundle["observable_speed_steering_event_experts"]
    )
    large_error_root = source.parent / "yaw_large_error_audit_v1"
    feature_ablation = json.loads((large_error_root /
        "yaw_group_feature_ablation_2packet_loco_r09.json").read_text(
            encoding="utf-8"))
    gt_diagnostic = json.loads((large_error_root /
        "gt_body_velocity_information_r09_two_packet.json").read_text(
            encoding="utf-8"))
    lines = [
        "# Exact-two-packet yaw atlas: held-out cell inventory — 2026-10-08",
        "",
        "This report is generated from the existing exact-two-packet audit. It",
        "uses held-out validation captures only for the table below; test and",
        "final-test partitions were not read. Speeds are floored to 1 m/s bins",
        "and signed physical steering is rounded to 0.1 rad. Each row compares",
        "the same validation cell for the global/event candidate and the",
        "directly supported local speed-steering-event expert bank.",
        "",
        "The local bank has no fallback: `local n` is the number of rows with a",
        "directly supported local expert; `all n` is the total exact-two rows",
        "in that cell. A dash means the cell has validation data but no local",
        "expert prediction. Zero rows means no exact-two validation data in the",
        "cell. Error columns are yaw-rate residuals in rad/s; they are not",
        "yaw-angle errors. The separate response-phase angle results are in",
        "`validation_atlas.json` and are teacher-forced one-step windows, not",
        "recursive free-running yaw trajectories.",
        "",
        "## Per-cell results",
        "",
        "| GT speed (m/s) | Signed steering (rad) | All n | Global RMSE | Global p95 | Global max | Global >0.1 | Local n / all n | Val runs | Local RMSE | Local p95 | Local max | Local >0.1 |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]

    for speed_bin in SPEED_BINS:
        for steer_tenths in STEERING_TENTHS:
            key = _cell_key(speed_bin, steer_tenths)
            broad = global_cells.get(key)
            local = local_cells.get(key)
            if broad is None:
                all_n = 0
                global_metric = None
            else:
                all_n = broad["yaw_rate_error"]["samples"]
                global_metric = broad["yaw_rate_error"]
            if local is None:
                local_n, runs, local_metric = 0, 0, None
            else:
                local_metric = local["yaw_rate_error"]
                local_n = local_metric["samples"]
                runs = local["independent_runs"]
            global_values = ["—"] * 4 if global_metric is None else [
                _fmt(global_metric["rmse_radps"]),
                _fmt(global_metric["p95_abs_radps"]),
                _fmt(global_metric["max_abs_radps"]),
                str(global_metric["samples_over_0p1_radps"]),
            ]
            local_values = ["—"] * 4 if local_metric is None else [
                _fmt(local_metric["rmse_radps"]),
                _fmt(local_metric["p95_abs_radps"]),
                _fmt(local_metric["max_abs_radps"]),
                str(local_metric["samples_over_0p1_radps"]),
            ]
            lines.append(
                f"| {speed_bin}–{speed_bin + 1} | {steer_tenths / 10:+.1f} | "
                f"{all_n} | {' | '.join(global_values)} | "
                f"{local_n} / {all_n} | {runs} | {' | '.join(local_values)} |"
            )

    supported_selector_cells = sum(
        (speed, steer + 5) in expert_counts
        for speed in range(12) for steer in range(-5, 6))
    lines.extend([
        "",
        "## Training expert coverage (causal selector grid)",
        "",
        "This grid counts fitted train-only experts selected by rear-wheel speed",
        "and signed steering-feedback bins. A value is the number of distinct",
        "causal event experts available in that cell; it is not a validation",
        "accuracy claim. Unlike the validation table above, this makes missing",
        "model cells explicit even when no validation sample happened to visit",
        "them. The 1 m/s × 0.1 rad grid is a finite resolution, not every real",
        "valued point in the continuous domain.",
        "",
        f"The fitted bank has {len(model_bundle['observable_speed_steering_event_experts'])} "
        f"event experts across {supported_selector_cells}/132 selector cells; "
        f"{132 - supported_selector_cells} cells have no local expert.",
        "",
        "| Rear-wheel speed cell (m/s) | "
        + " | ".join(f"{value:+.1f}" for value in np.arange(-0.5, 0.51, 0.1))
        + " |",
        "|---|" + "---:|" * 11,
    ])
    for speed in range(12):
        values = [str(expert_counts.get((speed, steering + 5), 0))
                  for steering in range(-5, 6)]
        lines.append(f"| {speed}–{speed + 1} | " + " | ".join(values) + " |")

    # Expose mismatches between the event seen in the scored response and the
    # causal event used to route the expert at prediction time.
    target = predictions["target_yaw_residual_radps"]
    local_prediction = predictions["predicted_local_residual_radps"]
    measured_event = predictions["measured_response_event"].astype(str)
    causal_event = predictions["causal_event"].astype(str)
    event_errors: dict[tuple[str, str], list[float]] = defaultdict(list)
    for measured, causal, prediction, truth in zip(
            measured_event, causal_event, local_prediction, target):
        if np.isfinite(prediction):
            event_errors[(measured, causal)].append(float(prediction - truth))

    lines.extend([
        "",
        "## Measured response phase versus causal expert route",
        "",
        "`Measured phase` is an offline label derived from the recorded response;",
        "it is for diagnosis only and cannot route a live observer. `Causal",
        "route` is the route actually used by the local predictor. Errors below",
        "are for the same exact-two validation rows as the main table.",
        "",
        "| Measured response phase | Causal route | n | RMSE | p95 | Max | >0.1 |",
        "|---|---|---:|---:|---:|---:|---:|",
    ])
    for (measured, causal), errors in sorted(event_errors.items()):
        values = np.asarray(errors, dtype=np.float64)
        absolute = np.abs(values)
        lines.append(
            f"| {measured} | {causal} | {len(values)} | "
            f"{_fmt(np.sqrt(np.mean(values * values)))} | "
            f"{_fmt(np.quantile(absolute, 0.95))} | "
            f"{_fmt(np.max(absolute))} | "
            f"{int(np.count_nonzero(absolute > 0.1))} |"
        )

    worst_cells = sorted(
        local_cells.items(),
        key=lambda item: (item[1]["yaw_rate_error"]["samples_over_0p1_radps"],
                          item[1]["yaw_rate_error"]["max_abs_radps"]),
        reverse=True,
    )[:12]
    lines.extend([
        "",
        "## Largest local-bank error groups",
        "",
        "These are held-out cell aggregates, not independent physical laws;",
        "the count above 0.1 rad/s highlights error mass while max exposes",
        "isolated tails.",
        "",
        "| GT speed cell | Steering cell | Val rows | Val runs | RMSE | p95 | Max | >0.1 |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ])
    for key, cell in worst_cells:
        metric = cell["yaw_rate_error"]
        lines.append(
            f"| {cell['gt_speed_interval_mps'][0]:.0f}–"
            f"{cell['gt_speed_interval_mps'][1]:.0f} | "
            f"{cell['steering_bin_center_rad']:+.1f} | {metric['samples']} | "
            f"{cell['independent_runs']} | {_fmt(metric['rmse_radps'])} | "
            f"{_fmt(metric['p95_abs_radps'])} | "
            f"{_fmt(metric['max_abs_radps'])} | "
            f"{metric['samples_over_0p1_radps']} |"
        )

    reversal_features = feature_ablation["groups"]["reversal/2_packet"]["summary"]
    unwind_features = feature_ablation["groups"]["unwind/2_packet"]["summary"]
    reversal_gt = gt_diagnostic["groups"]["reversal/2_packet"]["held_out_validation"]
    unwind_gt = gt_diagnostic["groups"]["unwind/2_packet"]["held_out_validation"]
    lines.extend([
        "",
        "## What explains the largest tails so far",
        "",
        "The exact-two validation cross-tab above shows the local route does not",
        "have a distinct causal `reversal` state. The offline measured response",
        "label is not allowed to choose a live model, but it exposes where the",
        "causal router is mixing response phases:",
        "",
        "- Measured reversal routed as hold: 4,722 rows; "
        "63 exceed 0.1 rad/s (max 0.620).",
        "- Measured reversal routed as turn-in: 1,474 rows; "
        "53 exceed 0.1 rad/s (max 0.323).",
        "- Measured reversal routed as unwind: 278 rows; "
        "65 exceed 0.1 rad/s (RMSE 0.140, max 0.886).",
        "- Measured unwind routed as hold: 2,298 rows; none exceed 0.1 rad/s;",
        "  measured unwind routed as unwind: 815 rows; 90 exceed 0.1 rad/s",
        "  (RMSE 0.099, max 1.007).",
        "",
        "Run-held-out exact-two feature ablation confirms steering actuator",
        "feedback/command history is essential, but the tested extra channels do",
        "not explain the residual tail. Removing steering-actuator features",
        f"changes reversal CV RMSE {reversal_features['full']['macro_rmse_radps']:.3f}→"
        f"{reversal_features['steering_actuator']['macro_rmse_radps']:.3f} rad/s "
        f"and >0.1 misses {reversal_features['full']['sum_samples_over_0p1']}→"
        f"{reversal_features['steering_actuator']['sum_samples_over_0p1']}; for unwind "
        f"it changes {unwind_features['full']['macro_rmse_radps']:.3f}→"
        f"{unwind_features['steering_actuator']['macro_rmse_radps']:.3f} rad/s and "
        f">0.1 misses {unwind_features['full']['sum_samples_over_0p1']}→"
        f"{unwind_features['steering_actuator']['sum_samples_over_0p1']}.",
        "",
        f"Adding IMU roll and roll rate instead gives reversal CV RMSE "
        f"{reversal_features['imu_roll_and_rate']['macro_rmse_radps']:.3f} "
        f"versus {reversal_features['full']['macro_rmse_radps']:.3f} rad/s, and "
        f"unwind {unwind_features['imu_roll_and_rate']['macro_rmse_radps']:.3f} "
        f"versus {unwind_features['full']['macro_rmse_radps']:.3f}. Rear-wheel, "
        "throttle, IMU-yaw-history, and receipt-timing ablations likewise do not "
        "remove the held-out failure tail.",
        "",
        "Simulator-truth body-motion information was also tested only as an",
        "offline diagnostic, never as a predictor input. On the independent",
        "packet-phase validation capture, adding GT body u/v did not improve",
        f"reversal RMSE ({reversal_gt['legal_sensor_only']['rmse_radps']:.3f}→"
        f"{reversal_gt['plus_forbidden_gt_body_u_v_diagnostic']['rmse_radps']:.3f} "
        "rad/s) or unwind RMSE "
        f"({unwind_gt['legal_sensor_only']['rmse_radps']:.3f}→"
        f"{unwind_gt['plus_forbidden_gt_body_u_v_diagnostic']['rmse_radps']:.3f} "
        "rad/s). Thus wheel/body speed mismatch and roll are not established as "
        "the missing universal cause. The best-supported explanation so far is "
        "a transition-phase/steering-response mismatch, with an incomplete causal "
        "event router; it is not yet a fully solved physical law.",
    ])

    coverage = report["model"]["local_speed_steering_event_extra_trees"][
        "validation_coverage_fraction"]
    fitted = report["model"]["local_speed_steering_event_extra_trees"][
        "fitted_expert_count"]
    exact = report["row_coverage"]["validation_exact_two"]
    local_summary = atlas["models"]["local_speed_steering_event_experts"]
    local_phase = local_summary["integrated_response_phase"]
    global_phase = atlas["models"]["causal_event_specialists"][
        "integrated_response_phase"]
    lines.extend([
        "",
        "## Coverage and angle-error interpretation",
        "",
        f"- Exact-two validation: {exact['rows']:,} rows, "
        f"{len(global_cells)} occupied center-based 1 m/s × 0.1 rad signed "
        f"cells ({sum(cell['yaw_rate_error']['samples'] >= 20 for cell in global_cells.values())} "
        f"have at least 20 rows); speed {exact['gt_speed_min_mps']:.2f}–"
        f"{exact['gt_speed_max_mps']:.2f} m/s, |steering| up to "
        f"{exact['abs_steering_max_rad']:.2f} rad.",
        f"- Local predictions appear in {len(local_cells)} / {len(global_cells)} "
        "occupied validation cells, but per-row local coverage is lower because "
        "not every maneuver event in those cells has a supported expert.",
        f"- The coarse local bank contains {fitted} experts and predicts "
        f"{coverage:.1%} of exact-two validation rows without fallback.",
        f"- Local-bank phase integration: {local_phase['fully_supported_phases']} / "
        f"{local_phase['joined_phases']} phases fully supported; maximum "
        f"cumulative absolute yaw-angle error "
        f"{local_phase['max_abs_cumulative_error_deg']:.3f}°; "
        f"{local_phase['phases_over_5deg']} supported phases above 5°.",
        f"- Causal-event model phase integration: "
        f"{global_phase['fully_supported_phases']} / "
        f"{global_phase['joined_phases']} phases fully supported; maximum "
        f"cumulative absolute yaw-angle error "
        f"{global_phase['max_abs_cumulative_error_deg']:.3f}°; "
        f"{global_phase['phases_over_5deg']} phases above 5°.",
        "- This does **not** certify the full requested domain: unsupported",
        "  cells are not counted as passing, and phase integration uses",
        "  one-step teacher-forced residuals rather than recursive rollout.",
        "  The exact-two dataset has no validation near 12 m/s and lacks the",
        "  high-speed/high-steering surface described in the parent audit.",
        "",
        "Source: `live_runs/racing_model_diagnostics_20261008/"
        "yaw_full_domain_exact_two_v2/validation_atlas.json` and `report.json`.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    report, atlas = _load(args.source)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(report, atlas, args.source), encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
