#!/usr/bin/env python3
"""Export the v2 LightGBM estimators as a dependency-free C++ header.

The training and scoring tools use LightGBM offline.  The racing node is C++
and must not import Python, simulator truth, or a calibration service, so this
script converts the two serialized tree ensembles into compact flat arrays.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import lightgbm as lgb


def _flatten_tree(node: dict, nodes: list[tuple[int, float, int, int, float]]) -> int:
    index = len(nodes)
    nodes.append((255, 0.0, 0, 0, 0.0))
    if "leaf_value" in node:
        nodes[index] = (255, 0.0, 0, 0, float(node["leaf_value"]))
        return index

    left = _flatten_tree(node["left_child"], nodes)
    right = _flatten_tree(node["right_child"], nodes)
    nodes[index] = (
        int(node["split_feature"]),
        float(node["threshold"]),
        left,
        right,
        0.0,
    )
    return index


def _flatten_model(path: Path) -> tuple[list[str], list[int], list[tuple[int, float, int, int, float]]]:
    booster = lgb.Booster(model_file=str(path))
    dump = booster.dump_model()
    roots: list[int] = []
    nodes: list[tuple[int, float, int, int, float]] = []
    for tree in dump["tree_info"]:
        roots.append(_flatten_tree(tree["tree_structure"], nodes))
    return list(booster.feature_name()), roots, nodes


def _format_values(values: list[object], formatter, width: int = 8) -> str:
    rows = []
    for offset in range(0, len(values), width):
        rows.append("    " + ", ".join(formatter(v) for v in values[offset:offset + width]) + ",")
    return "\n".join(rows)


def _emit_array(name: str, type_name: str, values: list[object], formatter, width: int = 8) -> str:
    return (
        f"  inline static constexpr std::array<{type_name}, {len(values)}> {name} = {{\n"
        f"{_format_values(values, formatter, width)}\n  }};\n"
    )


def _emit_model_arrays(prefix: str, roots: list[int], nodes: list[tuple[int, float, int, int, float]]) -> str:
    features = [node[0] for node in nodes]
    thresholds = [node[1] for node in nodes]
    left = [node[2] for node in nodes]
    right = [node[3] for node in nodes]
    values = [node[4] for node in nodes]
    return "".join([
        _emit_array(f"k{prefix}Roots", "int32_t", roots, lambda v: str(v), 12),
        _emit_array(f"k{prefix}Features", "uint8_t", features, lambda v: str(v), 16),
        _emit_array(f"k{prefix}Thresholds", "double", thresholds, lambda v: repr(v), 4),
        _emit_array(f"k{prefix}Left", "int32_t", left, lambda v: str(v), 12),
        _emit_array(f"k{prefix}Right", "int32_t", right, lambda v: str(v), 12),
        _emit_array(f"k{prefix}Values", "double", values, lambda v: repr(v), 4),
    ])


def _emit_evaluator(prefix: str, input_expression: str) -> str:
    return f"""    double {prefix.lower()}(const std::array<double, kFeatureCount> & input) const noexcept
    {{
      double sum = 0.0;
      for (const int32_t root : k{prefix}Roots) {{
        int32_t node = root;
        while (k{prefix}Features[static_cast<std::size_t>(node)] != 255U) {{
          const auto index = static_cast<std::size_t>(node);
          const auto feature = static_cast<std::size_t>(k{prefix}Features[index]);
          node = input[{input_expression}] <= k{prefix}Thresholds[index] ?
            k{prefix}Left[index] : k{prefix}Right[index];
        }}
        sum += k{prefix}Values[static_cast<std::size_t>(node)];
      }}
      return sum;
    }}
"""


def generate(global_model: Path, braking_model: Path, output: Path) -> None:
    global_features, global_roots, global_nodes = _flatten_model(global_model)
    braking_features, braking_roots, braking_nodes = _flatten_model(braking_model)
    global_index = {name: index for index, name in enumerate(global_features)}
    missing = [name for name in braking_features if name not in global_index]
    if missing:
        raise ValueError(f"braking features absent from global model: {missing}")
    braking_map = [global_index[name] for name in braking_features]

    arrays = _emit_model_arrays("Global", global_roots, global_nodes)
    arrays += _emit_model_arrays("Braking", braking_roots, braking_nodes)
    arrays += _emit_array("kBrakingFeatureMap", "uint16_t", braking_map, lambda v: str(v), 16)

    header = f"""// Generated by generate_odom_estimator_v2_header.py; do not edit by hand.
// Global model: {global_model.name} ({len(global_roots)} trees, {len(global_nodes)} nodes).
// Braking model: {braking_model.name} ({len(braking_roots)} trees, {len(braking_nodes)} nodes).
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace f1tenth_localization
{{

struct OdomEstimatorV2Prediction
{{
  double global_fractional_residual;
  double braking_absolute_residual_mps;
  bool valid;
}};

class OdomEstimatorV2Model final
{{
public:
  static constexpr std::size_t kFeatureCount = {len(global_features)};

  OdomEstimatorV2Prediction predict(
    const std::array<double, kFeatureCount> & input) const noexcept
  {{
    return {{global(input), braking(input), true}};
  }}

private:
{_emit_evaluator("Global", "feature")}
    double braking(const std::array<double, kFeatureCount> & input) const noexcept
    {{
      double sum = 0.0;
      for (const int32_t root : kBrakingRoots) {{
        int32_t node = root;
        while (kBrakingFeatures[static_cast<std::size_t>(node)] != 255U) {{
          const auto index = static_cast<std::size_t>(node);
          const auto feature = static_cast<std::size_t>(kBrakingFeatures[index]);
          node = input[kBrakingFeatureMap[feature]] <= kBrakingThresholds[index] ?
            kBrakingLeft[index] : kBrakingRight[index];
        }}
        sum += kBrakingValues[static_cast<std::size_t>(node)];
      }}
      return sum;
    }}

{arrays}}};

}}  // namespace f1tenth_localization
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(header)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("global_model", type=Path)
    parser.add_argument("braking_model", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    generate(args.global_model, args.braking_model, args.output)


if __name__ == "__main__":
    main()
