"""Run the official AutoDRIVE bridge with bounded 40 Hz request pacing.

The official bridge requests the next simulator telemetry packet from inside the
telemetry callback. Decoding images and publishing ROS messages therefore
couples request cadence to callback work. This wrapper retains the official
decoder and topic contract but schedules requests at 40 Hz while allowing at
most one outstanding request. If the simulator/bridge cannot complete a packet
before the next slot, that slot is skipped instead of queuing another request.
This prevents response backlog from being released as telemetry bursts.

No ROS sensor sample is fabricated, interpolated or repeated here. Incoming
telemetry is published only when the simulator returns a packet.
"""

from __future__ import annotations

import os
import threading
import time
from copy import copy
from typing import Any

from autodrive_roboracer import autodrive_bridge as official_bridge


DEFAULT_RATE_HZ = 40.0
_command_lock = threading.Lock()
_latest_command: dict[str, str] = {
    "V1 Throttle": "0.0",
    "V1 Steering": "0.0",
    "V1 Reset": "False",
}
_reset_level = False
_stop_sender = threading.Event()
_response_ready = threading.Event()
_packet_stamp_lock = threading.Lock()
_packet_stamp: Any = None
_pending_source_stamp_lock = threading.Lock()
_pending_source_stamp: Any = None
_packet_timestamp_patch_installed = False


def _copy_stamp(stamp: Any) -> Any:
    """Copy a ROS time value without sharing a mutable message object."""
    return copy(stamp)


def _set_pending_source_stamp() -> None:
    """Stamp the request that will produce the next telemetry packet.

    AutoDRIVE does not expose simulator physics time in the ROS bridge payload.
    With at most one outstanding request, request time is an unambiguous source
    acquisition boundary and is preferable to independently timestamping every
    publication helper on callback arrival.
    """
    global _pending_source_stamp
    node = getattr(official_bridge, "autodrive_bridge", None)
    if node is None:
        return
    try:
        stamp = node.get_clock().now().to_msg()
    except Exception:
        return
    with _pending_source_stamp_lock:
        _pending_source_stamp = _copy_stamp(stamp)


def _install_packet_timestamp_patch() -> None:
    """Give every ROS message generated by one telemetry packet one stamp.

    The official bridge calls ``get_clock().now()`` independently in each
    message-construction helper. The wrapper instead uses the timestamp of the
    single outstanding request that triggered this packet. If no request stamp
    is available (for example during initial connection), it falls back to the
    first native message stamp and still keeps the packet internally coherent.
    """
    global _packet_timestamp_patch_installed
    if _packet_timestamp_patch_installed:
        return

    def stamped_creator(original: Any) -> Any:
        def create(*args: Any, **kwargs: Any) -> Any:
            global _packet_stamp
            message = original(*args, **kwargs)
            if not hasattr(message, "header"):
                return message
            with _packet_stamp_lock:
                if _packet_stamp is None:
                    with _pending_source_stamp_lock:
                        pending = _pending_source_stamp
                    _packet_stamp = _copy_stamp(
                        pending if pending is not None else message.header.stamp)
                message.header.stamp = _copy_stamp(_packet_stamp)
            return message
        return create

    for name in (
        "create_joint_state_msg", "create_imu_msg", "create_odom_msg",
        "create_laserscan_msg", "create_image_msg", "create_tf_msg",
    ):
        if hasattr(official_bridge, name):
            setattr(official_bridge, name, stamped_creator(
                getattr(official_bridge, name)))

    original_encoder_publish = official_bridge.publish_encoder_data

    def begin_packet(*args: Any, **kwargs: Any) -> Any:
        global _packet_stamp
        with _packet_stamp_lock:
            _packet_stamp = None
        return original_encoder_publish(*args, **kwargs)

    original_collision_publish = official_bridge.publish_collision_count_data

    def end_packet(*args: Any, **kwargs: Any) -> Any:
        global _packet_stamp, _pending_source_stamp
        result = original_collision_publish(*args, **kwargs)
        with _packet_stamp_lock:
            _packet_stamp = None
        with _pending_source_stamp_lock:
            _pending_source_stamp = None
        return result

    official_bridge.publish_encoder_data = begin_packet
    official_bridge.publish_collision_count_data = end_packet
    _packet_timestamp_patch_installed = True


def _rate_hz() -> float:
    value = os.environ.get("AUTODRIVE_BRIDGE_RATE_HZ", str(DEFAULT_RATE_HZ))
    try:
        rate = float(value)
    except ValueError as exc:
        raise RuntimeError("AUTODRIVE_BRIDGE_RATE_HZ must be a positive number") from exc
    if rate <= 0.0:
        raise RuntimeError("AUTODRIVE_BRIDGE_RATE_HZ must be a positive number")
    return rate


def _remember_command(data: Any) -> None:
    global _reset_level
    if not isinstance(data, dict) or "V1 Throttle" not in data:
        return
    command = {
        "V1 Throttle": str(data.get("V1 Throttle", "0.0")),
        "V1 Steering": str(data.get("V1 Steering", "0.0")),
        "V1 Reset": str(data.get("V1 Reset", "False")),
    }
    with _command_lock:
        _reset_level = command["V1 Reset"].strip().lower() == "true"
        _latest_command.update(command)


def _run_command_sender(original_emit: Any, rate_hz: float) -> None:
    """Send at scheduled slots, never with more than one request outstanding."""
    period = 1.0 / rate_hz
    next_send = time.monotonic()
    while not _stop_sender.is_set():
        now = time.monotonic()
        wait_time = next_send - now
        if wait_time > 0.0:
            _stop_sender.wait(wait_time)
            continue

        next_send += period
        if next_send < now:
            missed = int((now - next_send) / period) + 1
            next_send += missed * period

        if not _response_ready.is_set():
            continue

        with _command_lock:
            command = dict(_latest_command)
            command["V1 Reset"] = "True" if _reset_level else "False"

        _response_ready.clear()
        _set_pending_source_stamp()
        try:
            original_emit("Bridge", data=command)
        except Exception as exc:
            _response_ready.set()
            print(f"[autodrive_bridge_40hz] command send failed: {exc}")


def main() -> None:
    rate_hz = _rate_hz()
    _install_packet_timestamp_patch()
    original_emit = official_bridge.sio.emit

    def intercept_emit(event: str, data: Any = None, *args: Any, **kwargs: Any) -> Any:
        if event == "Bridge":
            _remember_command(data)
            _response_ready.set()
            return None
        return original_emit(event, data, *args, **kwargs)

    official_bridge.sio.emit = intercept_emit
    _stop_sender.clear()
    _response_ready.set()
    sender = threading.Thread(
        target=_run_command_sender,
        args=(original_emit, rate_hz),
        name="autodrive-bridge-command-clock",
        daemon=True,
    )
    sender.start()
    print(
        f"[autodrive_bridge_40hz] bounded request pacing enabled at {rate_hz:g} Hz "
        "(max one outstanding request)")
    try:
        official_bridge.main()
    finally:
        _stop_sender.set()
        _response_ready.set()
        sender.join(timeout=max(1.0, 2.0 / rate_hz))
        official_bridge.sio.emit = original_emit


if __name__ == "__main__":
    main()
