<?xml version="1.0"?>
<package format="3">
  <name>f1tenth_localization</name>
  <version>2.0.0</version>
  <description>CUDA AMCL and encoder/IMU odometry for AutoDRIVE RoboRacer.</description>
  <maintainer email="akmun23@student.sdu.dk">Aksel Munksgaard-Ottosen</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ament_index_cpp</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>eigen</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
