scan_splitter_node:
  ros__parameters:
    enable_splitting: true
    scan_topic: /autodrive/roboracer_1/lidar
    obstacles_topic: /scan_obstacles
    map_topic: /map
    laser_frame: lidar
    map_frame: map
    obstacle_threshold: 0.18
    wall_tolerance: 0.18
    min_cluster_size: 4
    max_cluster_gap_beams: 1
    max_obstacle_width: 0.65
    enable_raycast_splitting: true
    occlusion_threshold: 0.25
    raycast_wall_hit_tolerance: 0.15
    raycast_step: 0.0
    raycast_max_range: 8.0
    limit_obstacle_fov: true
    obstacle_angle_min: -1.57079632679
    obstacle_angle_max: 1.57079632679
